export const types = {
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_ERRORS: 'SET_ERRORS',
    GET_CREATURES: 'GET_CREATURES',
    GET_CAMPAIGNS: 'GET_CAMPAIGNS',
    UPDATE_ROUTE: 'UPDATE_ROUTE',
    RESET_ROUTE: 'RESET_ROUTE'
};